name: Install dependencies
description: Installs project dependencies
runs:
  using: composite
  steps:
    - name: Find latest Python supported by Red-DiscordBot
      id: find_pyver
      shell: bash
      run: |
        PYVER=$(bash "$GITHUB_WORKSPACE/.github/find_latest_red_pyver.sh")
        echo "python-version=$PYVER" >> "$GITHUB_OUTPUT"
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ steps.find_pyver.outputs.python-version }}
    - name: Install cog dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement requirements.txt
    - name: Install CI dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement requirements-dev.txt
