name: Install dependencies
description: Installs project dependencies
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install base dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement requirements.txt
    - name: Install CI dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement requirements-dev.txt
    - name: Install cog dependencies
      shell: bash
      run: |
        python3 .github/actions/setup/compile_requirements.py
        pip install --quiet --upgrade --requirement requirements-cogs.txt
