name: Install dependencies
description: Installs project dependencies
runs:
  using: composite
  steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install base dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement requirements.txt
    - name: Install CI dependencies
      shell: bash
      run: pip install --quiet --upgrade --requirement .github/requirements-ci.txt
    - name: Install cog dependencies
      shell: bash
      run: |
        python3 .github/actions/setup/compile_requirements.py
        pip install --quiet --upgrade --requirement requirements-cogs.txt
