name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      # For the labeler, check out .github/labeler.yml for the configuration
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
