name: setup

on: [workflow_call]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository at the current branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install base dependencies
        run: pip install --quiet --upgrade --requirement requirements.txt
      - name: Install CI dependencies
        run: pip install --quiet --upgrade --requirement requirements-ci.txt
      - name: Install cog dependencies
        run: |
          python3 .github/scripts/compile_requirements.py
          pip install --quiet --upgrade --requirement requirements-cogs.txt
